/*CONSTRAINTS*/
/*INFO: 
1.If we are not giving 
name for constraint oracle DB
will automatically generate a name

2.If we are not giving name for 
constraint no need to mention 
CONSTRAINT keyword*/

/*1.NOT NULL CONSTRAINT*/
/*1.1. While creating table itself*/
CREATE TABLE KMR_PEOPLE(
ID NUMBER CONSTRAINT KMR_TABLE_ID_NN NOT NULL,
NAME VARCHAR2(100) CONSTRAINT KMR_TABLE_NAME_NN NOT NULL,
STREET VARCHAR2(100),
CITY VARCHAR2(100));

SELECT * FROM KMR_PEOPLE;
INSERT INTO KMR_PEOPLE (ID, NAME, STREET, CITY)
VALUES ('1','KMR','Street1','City1');

UPDATE KMR_PEOPLE
SET DOOR_NO = 10;

/*1.2.After creating table*/
ALTER TABLE KMR_PEOPLE
MODIFY DOOR_NO NUMBER CONSTRAINT KMR_PEOPLE_DOOR_NO_NN NOT NULL;
    
/*2.Unique Constraint*/
CREATE TABLE KMR_TEST(
NAME VARCHAR2(20),
ID NUMBER CONSTRAINT ID_NN NOT NULL CONSTRAINT ID_UQ UNIQUE);

SELECT * FROM KMR_TEST;

INSERT INTO KMR_TEST (NAME)
VALUES ('KMR');

/*2.1 Unique Constraint on table level*/
/*INFO : CONSTRAINT NAME SHOULD BE PROPER*/
CREATE TABLE KMR_NUMBER(
ID VARCHAR2(10),
TEST_1 NUMBER,
TEST_2 NUMBER,
CONSTRAINT TEST_UNIQ UNIQUE (TEST_1, TEST_2));

/*2.2 Unique constraint on alter table*/
/*INFO : CONSTRAINT NAME SHOULD BE UNIQUE AMONG DB*/
CREATE TABLE KMR_ALTER(
ID NUMBER CONSTRAINT ALTER_ID_NN NOT NULL CONSTRAINT ALTER_ID_UNQ UNIQUE,
FIRST_NAME VARCHAR2(10),
LAST_NAME VARCHAR2(10));

ALTER TABLE KMR_ALTER
ADD CONSTRAINT ALTER_2_UNQ UNIQUE (FIRST_NAME,LAST_NAME);

SELECT * FROM KMR_ALTER;

INSERT INTO KMR_ALTER 
VALUES('1','KMR','KMR');
INSERT INTO KMR_ALTER 
VALUES('2','KMR','KM');

